// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'
	| 'es'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	vue: NamespaceVueTranslation
}

type RootTranslation = {
	/**
	 * H​a​l​l​o​ ​{​n​a​m​e​}​!​ ​B​i​t​t​e​ ​h​i​n​t​e​r​l​a​s​s​e​ ​e​i​n​e​n​ ​S​t​e​r​n​,​ ​w​e​n​n​ ​d​i​r​ ​d​a​s​ ​P​r​o​j​e​k​t​ ​g​e​f​ä​l​l​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	hello: RequiredParams<'name'>
	/**
	 * W​e​l​t
	 */
	world: string
	/**
	 * {​{​K​e​i​n​|​E​i​n​|​Z​w​e​i​|​E​i​n​ ​p​a​a​r​|​e​i​n​i​g​e​|​v​i​e​l​e​}​}​ ​{​{​A​p​f​e​l​|​Ä​p​f​e​l​}​}
	 */
	apple: string
}

export type NamespaceVueTranslation = {
	/**
	 * V​i​t​e​ ​u​n​d​ ​V​u​e
	 */
	msg: string
}

export type Namespaces =
	| 'vue'

type DisallowNamespaces = {
	/**
	 * reserved for 'vue'-namespace\
	 * you need to use the `./vue/index.ts` file instead
	 */
	vue?: "[typesafe-i18n] reserved for 'vue'-namespace. You need to use the `./vue/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hallo {name}! Bitte hinterlasse einen Stern, wenn dir das Projekt gefällt: https://github.com/ivanhofer/typesafe-i18n
	 */
	hello: (arg: { name: string }) => LocalizedString
	/**
	 * Welt
	 */
	world: () => LocalizedString
	/**
	 * {{Kein|Ein|Zwei|Ein paar|einige|viele}} {{Apfel|Äpfel}}
	 */
	apple: (arg0: number | string | boolean) => LocalizedString
	vue: {
		/**
		 * Vite und Vue
		 */
		msg: () => LocalizedString
	}
}

export type Formatters = {}
